# Generated by Django 3.0.5 on 2020-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0012_auto_20200506_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['name'], 'verbose_name': 'Poder', 'verbose_name_plural': 'Poderes'},
        ),
        migrations.AlterField(
            model_name='metahuman',
            name='country',
            field=models.CharField(choices=[('US', 'United states'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('PL', 'Polonia'), ('WK', 'Wakanda'), ('LV', 'Lavteria'), ('RU', 'Rusia'), ('OT', 'Others')], max_length=2),
        ),
    ]
