<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-04-30 17:30
=======
# Generated by Django 3.0.5 on 2020-04-30 17:29
>>>>>>> 6948fa3ec2bf31c512f81f78cab02690591b5d62

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='level',
            field=models.IntegerField(default=50),
        ),
    ]
