# Generated by Django 3.0.5 on 2020-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0002_power_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
<<<<<<< HEAD
                ('country', models.CharField(choices=[('US', 'United States'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('OT', 'Others')], max_length=22)),
=======
                ('country', models.CharField(choices=[('US', 'United states'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('OT', 'Others')], max_length=2)),
>>>>>>> 6948fa3ec2bf31c512f81f78cab02690591b5d62
                ('level', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('powers', models.ManyToManyField(to='metahumans.Power')),
            ],
        ),
    ]
