# Generated by Django 3.0.5 on 2020-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0004_metahuman_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metahuman',
            old_name='alignment',
            new_name='ally',
        ),
    ]
