# Generated by Django 3.0.5 on 2020-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0005_auto_20200430_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metahuman',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('OT', 'Others')], max_length=22),
        ),
    ]
